# Generated by Django 5.2.13 on 2026-04-25 11:52

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_adminactionlog_id_alter_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=7)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('footer_text', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('enable_dark_mode', models.BooleanField(default=True)),
                ('layout_style', models.CharField(choices=[('MODERN', 'Modern & Clean'), ('BRUTALIST', 'Bold & Brutalist'), ('MINIMAL', 'Minimalist')], default='MODERN', max_length=20)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.client')),
            ],
        ),
    ]
