# Generated by Django 5.2.12 on 2026-04-25 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='vendors/favicons/')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('button_style', models.CharField(choices=[('rounded', 'Rounded'), ('square', 'Square'), ('pill', 'Pill')], default='rounded', max_length=50)),
                ('homepage_layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('banner', 'Banner Style')], default='grid', max_length=50)),
                ('featured_products_enabled', models.BooleanField(default=True)),
                ('hero_banner', models.ImageField(blank=True, null=True, upload_to='vendors/banners/')),
                ('font_family', models.CharField(default='Inter, sans-serif', max_length=100)),
                ('font_size_scale', models.FloatField(default=1.0)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
