# Generated by Django 5.2.12 on 2026-04-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='background_color',
            field=models.CharField(default='#f8f9fa', max_length=7),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='button_style',
            field=models.CharField(choices=[('rounded', 'Rounded'), ('square', 'Square'), ('pill', 'Pill')], default='rounded', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/favicons/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='featured_products_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='font_family',
            field=models.CharField(default='Inter, sans-serif', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='font_size_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='hero_banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/banners/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='homepage_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('banner', 'Banner Style')], default='grid', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='secondary_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
