# Generated by Django 5.2.12 on 2026-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('STAFF', 'Staff Admin'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10),
        ),
    ]
